"""Render REPORT.md from REPORT.template.md and numbers.json.

Placeholders: {{key}} or {{key|format}}. Every placeholder must resolve to a key in
numbers.json; an unknown key or a NaN value fails the render, so no number in the
report can be hand-typed or stale. Formats:
  int        1,234            pct      12.3%  (value is a share)
  t          1,234 t          kt       1.2 kt (thousand tonnes)
  cad        CAD 1,234        cad_m    CAD 1.2 million
  cad_t      CAD 1,234/t      ratio    0.87   signed_pct  -12.3% / +4.0%
  list       a, b, c          raw      str(value)
"""
from __future__ import annotations

import json
import math
import re
from pathlib import Path

PLACEHOLDER = re.compile(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*(?:\|\s*([a-z_]+))?\s*\}\}")


class ReportError(ValueError):
    pass


def _fmt(value, fmt: str | None) -> str:
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        raise ReportError("value is not finite")
    fmt = fmt or ("raw" if not isinstance(value, (int, float)) or isinstance(value, bool) else "int")
    if fmt == "raw":
        return str(value)
    if fmt == "list":
        return ", ".join(str(v) for v in value)
    if fmt == "int":
        return f"{value:,.0f}"
    if fmt == "pct":
        return f"{value * 100:.1f}%"
    if fmt == "signed_pct":
        return f"{value * 100:+.1f}%"
    if fmt == "t":
        return f"{value:,.0f} t"
    if fmt == "kt":
        return f"{value / 1000:,.1f} kt"
    if fmt == "cad":
        return f"CAD {value:,.0f}"
    if fmt == "cad_m":
        return f"CAD {value / 1e6:,.1f} million"
    if fmt == "cad_t":
        return f"CAD {value:,.0f}/t"
    if fmt == "ratio":
        return f"{value:.2f}"
    raise ReportError(f"unknown format {fmt!r}")


def render(template: str, numbers: dict) -> str:
    missing, bad = [], []

    def sub(m: re.Match) -> str:
        key, fmt = m.group(1), m.group(2)
        if key not in numbers:
            missing.append(key)
            return m.group(0)
        try:
            return _fmt(numbers[key]["value"], fmt)
        except ReportError as e:
            bad.append(f"{key}: {e}")
            return m.group(0)

    out = PLACEHOLDER.sub(sub, template)
    if missing or bad:
        raise ReportError("report placeholders unresolved: " + "; ".join([f"missing {k}" for k in missing] + bad))
    return out


def render_issue(issue_dir: Path) -> Path:
    template = (issue_dir / "REPORT.template.md").read_text(encoding="utf-8")
    numbers = json.loads((issue_dir / "outputs" / "numbers.json").read_text(encoding="utf-8"))["numbers"]
    out = issue_dir / "REPORT.md"
    header = "<!-- Generated by `make report` from REPORT.template.md and outputs/numbers.json. Edit the template, not this file. -->\n\n"
    out.write_text(header + render(template, numbers), encoding="utf-8")
    return out
